/**
 *
 * $Id$
 */
package e4modelextension.validation;

/**
 * A sample validator interface for
 * {@link e4modelextension.EditorPartDescriptor}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EditorPartDescriptorValidator {
	boolean validate();

	boolean validateUriFilter(String value);

	boolean validatePartAddingLogicUri(String value);
}
